### ISSUE TITLE
Spring Dependencies Don't Work with Spring 3.1.1

### ISSUE THREAD

**Issue by cepage** [skyscreamer/nevado#29]
Nevado has hard dependencies in the pom.xml on Spring versions earlier than 3.1, and this prevents it from running in applications that link to Spring 3.1.1

**Comment by carterpage** [comment]
What's the solution?  I could push spring up to 3.1.1, but wouldn't that cause problems for others on older version of spring who aren't ready to upgrade?

**Comment by cepage** [comment]
Try leaving the Spring version unspecified, or specify a minimum version of
3.0 if we use any features that require it. I don't think we have
dependencies on libraries that specify a Spring version number, so it
should take the most recent version by default. If someone pulls yoga into
their existing pom, it will use their specified Spring version, and our jar
should execute fine agains that.

Oh, and _HAPPY BIRTHDAY!_

On Thu, Jun 7, 2012 at 3:07 PM, Carter Page <
reply@reply.github.com

**Comment by carterpage** [comment]
I tried removing versions from the deps this morning, but it barfed on me.
 I thought that saying 3.0.3 meant the same as >= 3.0.3.  Not so?

On Thu, Jun 7, 2012 at 11:00 AM, Corby Page <
reply@reply.github.com

**Comment by cepage** [comment]
http://stackoverflow.com/questions/1922571/dependency-version-management-in-maven

On Thu, Jun 7, 2012 at 5:25 PM, Carter Page <
reply@reply.github.com

**Comment by carterpage** [comment]
I'm not able to reproduce.  The following pom.xml works fine:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nevado-spring</groupId>
    <artifactId>nevado-spring</artifactId>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>nevado-jms</artifactId>
            <version>1.0.0-Beta1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>3.1.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jms</artifactId>
            <version>3.1.0.RELEASE</version>
        </dependency>
    </dependencies>
```

**Comment by carterpage** [comment]
The only spring dependencies are in the test now, so there should be no more spring version conflicts for users.
