### ISSUE TITLE
Maven jar not uploaded

### ISSUE THREAD

**Issue by matthewdfleming** [skyscreamer/nevado#67]
It looks like the maven jar has not been uploaded to the main repo.. just the pom. Is this by design?

**Comment by carterpage** [comment]
The artifiactId is nevado-jms, not nevado (which is a placeholder for a parent project group).

Your pom dependency should like like:

```
<dependency>
  <groupId>org.skyscreamer</groupId>
  <artifactId>nevado-jms</artifactId>
  <version>1.2.5</version>
</dependency>
```

http://mvnrepository.com/artifact/org.skyscreamer/nevado-jms/1.2.5

**Comment by matthewdfleming** [comment]
Hmm.. that's what I had in there. I'm using a nexus repo as a proxy to the main maven repos and for some reason it isn't pulling stuff in. We use a corporate repo as the proxy so we just have one spot to fetch from but it doesn't seem to be working for this dependency.

**Comment by carterpage** [comment]
You can always download the JAR directly if you are having problems with maven:

https://github.com/skyscreamer/nevado/releases
