### ISSUE TITLE
com.xerox.amazonws.sqs2.QueueAttribute

### ISSUE THREAD

**Issue by xbranko** [skyscreamer/nevado#70]
This class is from typica's jar. Any chance to leave it out of your jar? You added QUEUE_ARN enum value that is not originally there. Typica's version doesn't have this, but TypicaSQSQueue.getQueueAttributes(QueueAttribute) needs a QueueAttribute -- so I see why it needed to be done somehow. Given that TypicaSQSQueue is deprecated, and QUEUE_ARN enum value is used only there, any chance it may be dropped in favor of amazonaws classes?

**Comment by carterpage** [comment]
We'll remove it entirely when we do a major release.  How is it causing your problems right now?

**Comment by xbranko** [comment]
In my company's centralized build environment there is a rule that no two jars can have the same class. Given that we already have typica, I cannot add nevado (because of com.xerox.amazonws.sqs2.QueueAttribute).

**Comment by carterpage** [comment]
Oh I see, you're talking about the override within Nevado, not the Typica
dependency.  Let me see what I can do.

**Comment by carterpage** [comment]
I'm looking at it, and it won't be super-straightforward.  I can't simply remove Typica with a patch release.  Some users depend on it.  I can look at other ways to refactor to get rid of the override (which I always found annoying besides).  Or maybe I can talk the Typica author into updating his enum.

**Comment by xbranko** [comment]
I understand. It might be hard to get typica update, the last release was 1.7.2. in July 2010. I wonder if it is an active project still. You mentioned a major release -- what is the time frame for that? Any chance of bringing it forward?

**Comment by carterpage** [comment]
I don't have one scheduled.  Maybe I'll remove it in a 1.3.0 release if I
can't get a response from the Typica dev.

**Comment by carterpage** [comment]
I've cut a 1.3.0 release with Typica removed.  It is available for download now at https://github.com/skyscreamer/nevado/releases.  It will appear on Maven repositories everywhere by the end of the week.

Thanks for reporting the issue.

**Comment by xbranko** [comment]
Thanks for the quick release! Really appreciate it! You might want to remove the comment referencing Typica too (In Readme.md file ).

**Comment by carterpage** [comment]
Good catch, thanks!
