### ISSUE TITLE
support for consuming of non-Nevado originated messages?

### ISSUE THREAD

**Issue by xbranko** [skyscreamer/nevado#76]
Consuming Nevado originated messages works as expected. What about the case when the messages were not created by Nevado producer? Right now the Hessian2Input class, in method startMessage checks if message starts with letter 'p' or 'P', and when it doesn't, it throws an HessianProtocolException.

Ideally the framework should be agnostic to the source of messages, as it is hard, and often impossible to force all producers to use the same framework. Sometimes they are not even written in the same language.

Any thoughts/suggestions?

**Comment by ChrisZ1** [comment]
This also pose a problem for me too. Digged  into the souce code and found code below, since NevadoQueue is the only type I know to define for SQS queue,  it will never go to the else branch.

```
    if (destination instanceof NevadoQueue)
    {
        messageBody = sqsMessage.getMessageBody();
    }
    else
    {
        try {
            messageBody = new JSONObject(sqsMessage.getMessageBody()).getString("Message");
        } catch (JSONException e) {
            throw new JMSException("Unable to parse JSON from message body: " + sqsMessage.getMessageBody());
        }
    }
```

**Comment by carterpage** [comment]
Nevado is a JMS provider which is more than a simple queue adapter, and
requires certain metadata to accompany the message.  Amazon does not
provide a way to send custom metadata with a message, so Nevado puts it in
a pojo and serializes that.

Maybe there's a way Nevado could analyze the message that comes in, and if
it's created by an external producer, set some reasonable metadata
defaults. I'll have to think about it.

**Comment by doctorwu** [comment]
Any thoughts yet? This also poses a problem for me. I have a python application that sends to a SNS topic which has a SQS subscriber. Then, there is a grails application which uses Nevado to consume the SQS messages.

**Comment by qc00** [comment]
I wrote a simple Connector like this

```
public class PlainTextAmazonSQSConnector extends AmazonAwsSQSConnector {

    public PlainTextAmazonSQSConnector(String awsAccessKey, String awsSecretKey, boolean isSecure,
            long receiveCheckIntervalMs) {
        super(awsAccessKey, awsSecretKey, isSecure, receiveCheckIntervalMs);
    }

    @Override
    protected String serializeMessage(NevadoMessage message) throws JMSException {
        if (message instanceof TextMessage) {
            return ((TextMessage) message).getText();
        } else {
            throw new UnsupportedOperationException(getClass().getSimpleName() + " does not support " + message);
        }
    }

    @Override
    protected NevadoMessage deserializeMessage(String serializedMessage) throws JMSException {
        NevadoTextMessage out = new NevadoTextMessage();
        out.setText(serializedMessage);
        return out;
    }

}
```

and created a matching SQSConnectorFactory and it now works like a charm.

**Comment by carterpage** [comment]
Would anyone else like to see billcn's Connector in Nevado?

**Comment by adinzbmason** [comment]
Yes please. Most of our messaging is fairly simple and we also have a need to interact with non-Java platforms.

In the longer term it would be great to extend this to support the newly added support for custom meta-data on messages. http://aws.amazon.com/blogs/aws/simple-queue-service-message-attributes/

**Comment by carterpage** [comment]
@billccn would you mind submitting a PR with your connector?

**Comment by qc00** [comment]
See pull request #94

**Comment by carterpage** [comment]
Merged.  I'll have a new version out next week.  Thanks for the contrib @billccn!
